---
title: "Homework 5 Writeup"
---
## Task 1 Writeup

In task 1, we used shiny package in R to create a web app that will allow the users to specify different priors and parameterizations and output the posterior distribution. 

### 1) ui.R

First we created the UI file to make users input parameters and then display the density of priors. `fluidpage` function creates a fluid page that layout. Inside this function, we first use `titlePanel` to create a panel which contains our application title, "Approximate Computing with Socks". Then we use `sidebarLayout` to create the layout of sidebar that contains multiple panels in which users input the socks parameters. Inside sidebarPanel, we use 5 `sidebarInput ` functions for inputting priors, which are *Prior Mean Number of Socks*, *Prior Std Deviation of Socks*, *Prior Fraction of Paired Socks*, *Prior Std Deviation of Paired Socks* and *Number of Socks Picked*. 

Then we use `mainPanel` to show three different `tabPanel` elements that include the description of this web app, the generated prior distribution, and the prior distribution. For the "Description" tabPanel, we used `htmlOutput` function to crete an HTML output element 'descript'. Then we create a conditional `actionButton` which will only show the answer if we click the button. 

For the "Prior Plots" tabPanel, we specified the layout of the two density plots. In the last tablet, "Posterior Plot", we output the posterior distribution, summary statistics, and a conditonal action button that shows the posterior median when clicked. 


### 2) server.R

In the second file, we create a server function to define server logic required to output the simulate socks and draw the density plots. 

First we use `observe` function to limit the domain of *prior_sd*. Based on the parameterization formula, we need the prior standard deviation greater than prior mean to obtain a positive prior size.

Then we define the object "sock_sim""; we use `reactive` function to pass the input to server function even when the inputs change, without having to change any codes. We set to generate 10,000 samples.

Our input parameters are *prior_mean*, *prior_sd*, *n_pick*, *frac_pair* and *sig_pair*, which are prior mean number of socks, prior standard deviation of the mean, prior fraction of paired socks, prior standard deviation of the fraction and number of socks picked. Our first goal is to calculate the prior size, where we got the formula from website [tiny data and the socks of karl broman] (http://www.sumsar.net/blog/2014/10/tiny-data-and-the-socks-of-karl-broman/). We also get the formula for α and β parameters in Beta distribution from website [Beta distribution parameter calculation](http://stats.stackexchange.com/questions/12232/calculating-the-parameters-of-a-beta-distribution-using-the-mean-and-variance). 

Then we generate a sample of the parameters from the priors. The parameters are `n_socks`, i.e number of socks in Karl Broman’s laundry, `frac_pairs`, i.e proportion of socks that come in pairs, `n_pairs` , i.e number of paired socks and `n_odd`, i.e number of unpaired socks in the laundry. Then we create a vector of socks as integers where each pair/singleton is given a unique number by using `rep()` function. We also simulate the process of picking out `n_picked` socks and counting the number of paired and unique socks. Finally, we use a vector to return the parameters and counts of the number of matched and unique socks among the picked-outs. 

In order to turn the simulated samples sock_sim into posterior samples, we need to throw away those simulations that do not match the actual data. In this case remove all simulated samples in which paried socks exist.

Then we use `renderPlot` function that renders a reactive plot suitable for assigning to the output slot. We plot a nbinom distribution for Negative Binomial Prior, plot prior beta distribution and a posterior density of the numbers of socks for Posterior Distribution of Socks.

Additionally, we use `renderPrint` to create a summary table that shows the min, quntile, max, median and mean for the post data.  Note that an error message will show up if the length of posterior distribution is less than 2 due to the insufficient sample size. The action button "postoerior median" shows the line of poasterior median when clicked. The output also includes the description for our webapp using `renderUI` and answer for the socks_button using `renderText`. 

Finally, we use `shinyApp` to run the application.




## Task 2 Writeup

In this problem, we try to speed up our shiny App. After examining both server.R and ui.R, we find that the only part that we can modify is *sock_sim* since other functions and commands don't include any iterations. The way we improve the runtime of our code is making use of multiple cores. To do that, we use the *mclapply* function, which splits the sampling into 10 parts with each part sampling 1000 values and utilizes multiple cores to generate all 10 sampling parts. In our case, we choose the core number to be the number of cores detected. The *mclapply* function greatly reduces our runtime, as it takes less than 1 second for the posterior density plot to appear when we make adjustments to the sidebars. Without using multiple cores, it takes a couple of seconds.